# Generated by Django 4.2.7 on 2026-05-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='resources.engineer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='resources.equipment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='resources.room'),
        ),
    ]
