# Generated by Django 4.2.7 on 2026-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_notes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time'], name='bookings_bo_start_t_3f3843_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'start_time'], name='bookings_bo_room_id_2520ec_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['engineer', 'start_time'], name='bookings_bo_enginee_0428ca_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'start_time'], name='bookings_bo_client__b5f1e4_idx'),
        ),
    ]
