# Generated by Django 4.2.7 on 2026-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_invoice_billing_inv_status_541249_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["issued_at", "status"], name="billing_inv_issued__be96ef_idx"),
        ),
    ]
