# Generated by Django 4.2.7 on 2026-06-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_issued_status_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_issued__381a44_idx',
            old_name='billing_inv_issued__be96ef_idx',
        ),
    ]
