# Generated by Django 4.2.7 on 2026-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('staff', 'Staff')], default='engineer', max_length=20),
        ),
    ]
